version: "2"                                                                          
                                                                                      
services:                                                                             
  nginx-proxy:                                                                        
    restart: always                                                                   
    container_name: "nginx-proxy"                                                     
    image: jwilder/nginx-proxy:alpine                                                 
    labels:                                                                           
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"               
    ports:                                                                            
      - "80:80"                                                                       
      - "443:443"                                                                     
    volumes:                                                                          
      - /var/run/docker.sock:/tmp/docker.sock:ro                                      
      - /etc/nginx/certs:/etc/nginx/certs:ro                                          
      - /etc/nginx/vhost.d                                                            
      - /usr/share/nginx/html                                                         
    networks:                                                                         
      - nginx-proxy                                                                   
                                                                                      
  nginx-letsencrypt-companion:                                                        
    restart: always                                                                   
    depends_on:                                                                       
      - nginx-proxy                                                                   
    image: jrcs/letsencrypt-nginx-proxy-companion                                     
    volumes_from:                                                                     
      - nginx-proxy                                                                   
    volumes:                                                                          
      - /var/run/docker.sock:/var/run/docker.sock:ro                                  
      - /etc/nginx/certs:/etc/nginx/certs:rw                                          
    networks:                                                                         
      - nginx-proxy                                                                   
                  
networks:
  nginx-proxy:
    external:
      name: nginx-proxy

